"""Put the Tendra Hand V1 on its forearm with a forearm twist and a 2-way wrist (MuJoCo MJCF).

Input:  sim/models/tendra_hand_v1.xml (generated by sim/convert_v1.py; the forearm and palm are
        both fixed to the world there)
Output: sim/models/tendra_hand_v1_wrist.xml

    uv run python sim/convert_v1_wrist.py       # re-run after every convert_v1.py run

This is the part of the arm below OpenArm's elbow (software/tendra/arm.py puts it on OpenArm's
shoulder and elbow). Three joints between the elbow and the palm, like a human arm:

- forearm_rot: the whole forearm turns about its long axis, positive = pronation (for this right
  hand: the palm turns toward the back of the hand's thumb side, palm down when the forearm is
  held out horizontally). Its motor is OpenArm's J5 (DM4310), which sits at the bottom of
  OpenArm's elbow link; the forearm's bottom face bolts to its flange (site `forearm_flange`).
- wrist_flex (positive = the palm bends toward the palm side, -Y) and wrist_dev (positive =
  toward the thumb, radial deviation): a gimbal whose two axes cross at one point, the wrist
  centre, in a WRIST_GAP-high gap between the forearm and the palm (about a human's carpal
  bones). The palm and fingers move up by WRIST_GAP compared with the hand model. How the wrist
  is driven is still open; the actuators are placeholders.

Tendons: the 32 servo strands cross the wrist in PTFE sheaths through the gimbal's hollow centre
(owner's choice, 2026-10-02), like a bicycle brake cable: each sheath is fixed in the forearm and
in the palm, so bending the wrist does not change the length of the strand inside it, and the
fingers don't move. The model routes every strand through one site on the wrist centre, a point
that no wrist angle moves, so this is exactly that ideal: no coupling. Not modelled: friction in
the bent sheaths, which grows with the wrist angle (capstan effect).

Because the strands are longer (the detour to the centre and the gap), the servo actuators'
offsets are measured again so that ctrl = 0 still means a straight joint.
"""

from __future__ import annotations

import copy
import math
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
IN_PATH = ROOT / "sim" / "models" / "tendra_hand_v1.xml"
OUT_PATH = ROOT / "sim" / "models" / "tendra_hand_v1_wrist.xml"

MM = 0.001
DEG = math.pi / 180.0

# Hand model frame (the Fusion export): X = thumb side, Y = back of the hand, Z = along the fingers.
FOREARM_AXIS = np.array([-33.5, 25.5]) * MM  # x, y of the forearm's long axis (its centre)
FLANGE_Z = -153.0 * MM  # forearm bottom face: OpenArm's J5 flange
WRIST_PLANE_Z = -30.0 * MM  # where the palm meets the forearm in the hand model
WRIST_GAP = 20.0 * MM  # the gimbal's room between forearm and palm; the palm moves up by this
WRIST_CENTRE = np.array([*FOREARM_AXIS, WRIST_PLANE_Z + WRIST_GAP / 2])  # on the forearm axis
PALM_SHIFT = np.array([0.0, 0.0, WRIST_GAP])

GIMBAL_MASS = 0.05  # kg, placeholder until the wrist is designed

# name: (body, axis, limits (deg), kp (N*m/rad), kv (N*m*s/rad), torque limit (N*m),
#        armature (kg*m^2), damping (N*m*s/rad), frictionloss (N*m))
# forearm_rot uses OpenArm's J5 (DM4310) values. The wrist values are placeholders: holding the hand
# (~0.4 kg, centre of mass ~70 mm out) and a 0.5 kg object 100 mm out needs < 1 N*m.
ARM_JOINTS = {
    "forearm_rot": ("forearm", (0, 0, -1), (-90, 90), 30.0, 1.5, 7.0, 0.01, 0.9, 0.04),
    "wrist_flex": ("wrist_gimbal", (1, 0, 0), (-60, 70), 10.0, 0.3, 2.0, 0.002, 0.1, 0.0),
    "wrist_dev": ("palm", (0, 1, 0), (-30, 20), 10.0, 0.3, 2.0, 0.002, 0.1, 0.0),
}

CENTRE_SITE = "wrist_centre"
FLANGE_SITE = "forearm_flange"


def _fmt(values, digits: int = 6) -> str:
    return " ".join(f"{v:.{digits}g}" for v in np.asarray(values, dtype=float).ravel())


def _pos(el: ET.Element) -> np.ndarray:
    return np.array([float(v) for v in el.get("pos", "0 0 0").split()])


def transform(hand: ET.Element) -> ET.Element:
    """The wrist model (MJCF tree) from the V1 hand model (MJCF tree); `hand` is not changed.
    Actuator offsets and keyframes still need `finish()` (they need a compile)."""
    root = copy.deepcopy(hand)
    root.set("model", "tendra_hand_v1_wrist")
    world = root.find("worldbody")
    bodies = {b.get("name"): b for b in world.findall("body")}
    forearm, palm = bodies["forearm"], bodies["palm"]
    for name, body in bodies.items():
        if body.get("pos") or body.find("joint") is not None:
            raise ValueError(f"expected {name} fixed to the world at the origin")

    # Forearm: turns about its axis. Every other fixed part except the palm (servos, spools) is
    # mounted in it. Forearm frame = world frame at q = 0.
    def arm_joint(name: str, pos: np.ndarray | None = None) -> ET.Element:
        _, axis, (lo, hi), _, _, _, armature, damping, friction = ARM_JOINTS[name]
        attrs = {"name": name, "axis": _fmt(axis), "range": _fmt([lo * DEG, hi * DEG])}
        if pos is not None:
            attrs["pos"] = _fmt(pos)
        attrs |= {"armature": _fmt([armature]), "damping": _fmt([damping])}
        if friction:
            attrs["frictionloss"] = _fmt([friction])
        return ET.Element("joint", attrs)

    forearm.insert(0, arm_joint("forearm_rot", np.array([*FOREARM_AXIS, FLANGE_Z])))
    for name, body in bodies.items():
        if name not in ("forearm", "palm"):
            world.remove(body)
            forearm.append(body)
    ET.SubElement(forearm, "site", name=FLANGE_SITE, pos=_fmt([*FOREARM_AXIS, FLANGE_Z]),
                  size="0.004", group="4")  # fmt: skip
    ET.SubElement(forearm, "site", name=CENTRE_SITE, pos=_fmt(WRIST_CENTRE), size="0.002",
                  group="4")  # fmt: skip

    # Gimbal: wrist_flex about X through the centre, then the palm about Y through the same point.
    gimbal = ET.SubElement(forearm, "body", name="wrist_gimbal", pos=_fmt(WRIST_CENTRE))
    gimbal.append(arm_joint("wrist_flex"))
    ET.SubElement(gimbal, "inertial", pos="0 0 0", mass=_fmt([GIMBAL_MASS]),
                  diaginertia="1e-05 1e-05 1e-05")  # fmt: skip
    pin = {"type": "capsule", "material": "gimbal", "contype": "0", "conaffinity": "0",
           "density": "0", "size": "0.004"}  # fmt: skip
    ET.SubElement(gimbal, "geom", name="wrist_flex_pin", fromto="-0.03 0 0 0.03 0 0", **pin)
    ET.SubElement(gimbal, "geom", name="wrist_dev_pin", fromto="0 -0.016 0 0 0.016 0", **pin)
    world.remove(palm)
    palm.set("pos", _fmt(PALM_SHIFT - WRIST_CENTRE))
    palm.insert(0, arm_joint("wrist_dev", WRIST_CENTRE - PALM_SHIFT))
    gimbal.append(palm)
    ET.SubElement(root.find("asset"), "material", name="gimbal", rgba="0.3 0.3 0.32 1")

    # Strand points that were fixed to the world: above the wrist plane in the palm, below it in
    # the forearm. Positions stay the same numbers (both bodies' frames were the world frame).
    site_body: dict[str, str] = {}
    for site in world.findall("site"):
        world.remove(site)
        target = palm if _pos(site)[2] >= WRIST_PLANE_Z - 1e-9 else forearm
        target.append(site)
    for body in root.iter("body"):
        for site in body.findall("site"):
            site_body[site.get("name")] = body.get("name")

    # Each strand: spool (forearm) ... palm. One sheath crossing: insert the wrist centre.
    for spatial in root.find("tendon").findall("spatial"):
        items = list(spatial)
        in_forearm = [el.tag == "site" and site_body[el.get("site")] == "forearm" for el in items]
        if not any(in_forearm):
            continue  # e.g. a DIP linkage bar, inside one finger
        n = in_forearm.index(False)
        if not all(in_forearm[:n]) or any(in_forearm[n:]):
            raise ValueError(f"{spatial.get('name')}: forearm points must come first, together")
        spatial.insert(n, ET.Element("site", site=CENTRE_SITE))

    # Collisions: the palm sits close to the forearm and its parts; MuJoCo only filters direct
    # parent-child pairs (here forearm-gimbal and gimbal-palm).
    contact = root.find("contact")
    if contact is None:
        contact = ET.SubElement(root, "contact")
    for body in forearm.iter("body"):
        name = body.get("name")
        if body is forearm or (body.find("joint") is None and name != "wrist_gimbal"):
            ET.SubElement(contact, "exclude", body1="palm", body2=name)

    actuator = root.find("actuator")
    for name, (_, _, (lo, hi), kp, kv, limit, *_) in ARM_JOINTS.items():
        ET.SubElement(actuator, "position", name=name, joint=name, kp=_fmt([kp]), kv=_fmt([kv]),
                      ctrlrange=_fmt([lo * DEG, hi * DEG]),
                      forcerange=_fmt([-limit, limit]))  # fmt: skip
    return root


def _compile(mjcf: ET.Element, meshdir: Path):
    import mujoco

    probe = copy.deepcopy(mjcf)
    probe.find("compiler").set("meshdir", meshdir.as_posix())
    keyframe = probe.find("keyframe")  # its qpos sizes may not match yet
    if keyframe is not None:
        probe.remove(keyframe)
    return mujoco.MjModel.from_xml_string(ET.tostring(probe, encoding="unicode"))


def finish(wrist: ET.Element, hand: ET.Element, meshdir: Path) -> ET.Element:
    """Measure the strands at q = 0 for the servo actuators' offsets, and carry the hand's keyframes
    over (arm joints at 0)."""
    import mujoco

    model = _compile(wrist, meshdir)
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)
    lengths = {model.tendon(i).name: float(data.ten_length[i]) for i in range(model.ntendon)}
    for act in wrist.find("actuator").findall("general"):
        # Servo actuators (convert_v1.py): length = gear * L, ctrl = joint angle, bias[0] =
        # -kp * offset with offset = L0 / r = -gear * L0.
        kp, gear = float(act.get("gainprm").split()[0]), float(act.get("gear"))
        bias = act.get("biasprm").split()
        bias[0] = f"{kp * gear * lengths[act.get('tendon')]:.12g}"
        act.set("biasprm", " ".join(bias))

    keyframe = wrist.find("keyframe")
    if keyframe is not None:
        hand_model = _compile(hand, meshdir)
        hand_order = [hand_model.joint(i).name for i in range(hand_model.njnt)]
        order = [model.joint(i).name for i in range(model.njnt)]
        for key in keyframe.findall("key"):
            q = dict(zip(hand_order, map(float, key.get("qpos").split()), strict=True))
            key.set("qpos", _fmt([q.get(n, 0.0) for n in order]))
            key.set("ctrl", key.get("ctrl") + " " + _fmt(np.zeros(len(ARM_JOINTS))))
    return wrist


def build(in_path: Path = IN_PATH) -> ET.Element:
    hand = ET.parse(in_path).getroot()
    meshdir = (in_path.parent / hand.find("compiler").get("meshdir")).resolve()
    wrist = finish(transform(hand), hand, meshdir)
    ET.indent(wrist)
    return wrist


def main() -> None:
    mjcf = build()
    header = (
        "<!-- GENERATED by sim/convert_v1_wrist.py from sim/models/tendra_hand_v1.xml. "
        "Do not edit by hand: change convert_v1_wrist.py (or convert_v1.py) and re-run them. -->\n"
    )
    OUT_PATH.write_text(
        header + ET.tostring(mjcf, encoding="unicode") + "\n", encoding="utf-8", newline="\n"
    )
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
